CREATE VIEW VIEW_OPOR_PUNKT (ID,NO_PR,NO_PK,GRAV,NO_GRAV,OP_DATE,"COMMENT",FK_PLOSHAD_ID,OTKL2,KRATN,GSREDN,SKP)
AS
SELECT a.ID, a.NO_PR, a.NO_PK, a.GRAV, a.NO_GRAV, a.OP_DATE, a."COMMENT", a.FK_PLOSHAD_ID
, c.OTKL2, c.KRATN, c.GSREDN, c.SKP
FROM OPOR_PUNKT a left join control c
on a.FK_PLOSHAD_ID=c.FK_PLOSHAD_ID and a.NO_PR=c.NO_PR and a.NO_PK=c.NO_PK and c.control=1
;
